# Generated by Django 4.2.5 on 2024-01-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expires_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
